config/routes.rb
Rails.application.routes.draw do
  get 'admin', to: 'admin#home'

  get 'admin/froms', to: 'admin_froms#index'
  get 'admin/froms/new', to: 'admin_froms#new'
  get 'admin/froms/:id', to: 'admin_froms#show'
  get 'admin/froms/:id/edit', to: 'admin_froms#edit'

  get 'admin/tournaments', to: 'admin_tournaments#index'
  get 'admin/tournaments/new', to: 'admin_tournaments#new'
  get 'admin/tournaments/:id', to: 'admin_tournaments#show'
  get 'admin/tournaments/:id/edit', to: 'admin_tournaments#edit'

  get 'admin/movies', to: 'admin_movies#index'
  get 'admin/movies/new', to: 'admin_movies#new'
  get 'admin/movies/:id', to: 'admin_movies#show'
  get 'admin/movies/:id/edit', to: 'admin_movies#edit'

  get 'admin/players', to: 'admin_players#index'
  get 'admin/players/new', to: 'admin_players#new'
  get 'admin/players/:id', to: 'admin_players#show'
  get 'admin/players/:id/edit', to: 'admin_players#edit'

  #get 'movies/', to: 'match_movies#index'
  #get 'movies/search', to: 'match_movies#search'
  post 'movies/search', to: 'match_movies#search'
  get 'movies/:id', to: 'match_movies#show'

  root 'match_movies#search'
end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/from.rb
class From < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/tournament.rb
class Tournament < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    def home
    end
end

app/controllers/admin_froms_controller.rb
class AdminFromsController < ApplicationController
  def show
  end

  def index
  end

  def edit
  end

  def new
  end
end

app/controllers/admin_movies_controller.rb
class AdminMoviesController < ApplicationController
  def show
  end

  def index
  end

  def edit
  end

  def new
  end
end

app/controllers/admin_players_controller.rb
class AdminPlayersController < ApplicationController
  def show
  end

  def index
  end

  def edit
  end

  def new
  end
end

app/controllers/admin_tournament_controller.rb
class AdminTournamentController < ApplicationController
  def show
  end

  def index
  end

  def edit
  end

  def new
  end
end

app/controllers/admin_tournaments_controller.rb
class AdminTournamentsController < ApplicationController
  def show
  end

  def index
  end

  def edit
  end

  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def root
        render html: "this is root!"
    end
end

app/controllers/match_movies_controller.rb
class MatchMoviesController < ApplicationController
  def index
    @movies = Movie.all
    @tournaments = Movie.all.distinct.pluck(:tournament_id)

    @all_tournaments = Tournament.all.pluck(:tournament)
    @all_players = Player.all.pluck(:name)
  end

  def search
    if params[:key]
      # 検索
      @player_id_list = []
      player_id_by_name_list = Player.where("name LIKE ?", "%" + params[:key] + "%").pluck(:id)
      player_id_by_affiliation_list = Affiliation.where("affiliation LIKE ?", "%" + params[:key] + "%").pluck(:player_id)
      @player_id_list.concat(player_id_by_name_list, player_id_by_affiliation_list)

      tournament_id_list = Tournament.where("tournament LIKE ?", "%" + params[:key] + "%").pluck(:id)

      @movies = Movie.where(player_a_id: @player_id_list).or(Movie.where(player_b_id: @player_id_list)).or(Movie.where(player_c_id: @player_id_list)).or(Movie.where(player_d_id: @player_id_list)).or(Movie.where(tournament_id: tournament_id_list)).distinct
      @tournaments = Movie.where(player_a_id: @player_id_list).or(Movie.where(player_b_id: @player_id_list)).or(Movie.where(player_c_id: @player_id_list)).or(Movie.where(player_d_id: @player_id_list)).or(Movie.where(tournament_id: tournament_id_list)).distinct.pluck(:tournament_id)

      @all_tournaments = Tournament.all.pluck(:tournament)
      @all_players = Player.all.pluck(:name)
    end
  end
end

app/helpers/admin_froms_helper.rb
module AdminFromsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_movies_helper.rb
module AdminMoviesHelper
end

app/helpers/admin_players_helper.rb
module AdminPlayersHelper
end

app/helpers/admin_tournament_helper.rb
module AdminTournamentHelper
end

app/helpers/admin_tournaments_helper.rb
module AdminTournamentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/match_movies_helper.rb
module MatchMoviesHelper
end

app/views/admin_froms/edit.html.erb
<h1>AdminFroms#edit</h1>
<p>Find me in app/views/admin_froms/edit.html.erb</p>

app/views/admin_froms/index.html.erb
<h1>AdminFroms#index</h1>
<p>Find me in app/views/admin_froms/index.html.erb</p>

app/views/admin_froms/new.html.erb
<h1>AdminFroms#new</h1>
<p>Find me in app/views/admin_froms/new.html.erb</p>

app/views/admin_froms/show.html.erb
<h1>AdminFroms#show</h1>
<p>Find me in app/views/admin_froms/show.html.erb</p>

app/views/admin_movies/edit.html.erb
<h1>AdminMovies#edit</h1>
<p>Find me in app/views/admin_movies/edit.html.erb</p>

app/views/admin_movies/index.html.erb
<h1>AdminMovies#index</h1>
<p>Find me in app/views/admin_movies/index.html.erb</p>

app/views/admin_movies/new.html.erb
<h1>AdminMovies#new</h1>
<p>Find me in app/views/admin_movies/new.html.erb</p>

app/views/admin_movies/show.html.erb
<h1>AdminMovies#show</h1>
<p>Find me in app/views/admin_movies/show.html.erb</p>

app/views/admin_players/edit.html.erb
<h1>AdminPlayers#edit</h1>
<p>Find me in app/views/admin_players/edit.html.erb</p>

app/views/admin_players/index.html.erb
<h1>AdminPlayers#index</h1>
<p>Find me in app/views/admin_players/index.html.erb</p>

app/views/admin_players/new.html.erb
<h1>AdminPlayers#new</h1>
<p>Find me in app/views/admin_players/new.html.erb</p>

app/views/admin_players/show.html.erb
<h1>AdminPlayers#show</h1>
<p>Find me in app/views/admin_players/show.html.erb</p>

app/views/admin_tournament/edit.html.erb
<h1>AdminTournament#edit</h1>
<p>Find me in app/views/admin_tournament/edit.html.erb</p>

app/views/admin_tournament/index.html.erb
<h1>AdminTournament#index</h1>
<p>Find me in app/views/admin_tournament/index.html.erb</p>

app/views/admin_tournament/new.html.erb
<h1>AdminTournament#new</h1>
<p>Find me in app/views/admin_tournament/new.html.erb</p>

app/views/admin_tournament/show.html.erb
<h1>AdminTournament#show</h1>
<p>Find me in app/views/admin_tournament/show.html.erb</p>

app/views/admin_tournaments/edit.html.erb
<h1>AdminTournaments#edit</h1>
<p>Find me in app/views/admin_tournaments/edit.html.erb</p>

app/views/admin_tournaments/index.html.erb
<h1>AdminTournaments#index</h1>
<p>Find me in app/views/admin_tournaments/index.html.erb</p>

app/views/admin_tournaments/new.html.erb
<h1>AdminTournaments#new</h1>
<p>Find me in app/views/admin_tournaments/new.html.erb</p>

app/views/admin_tournaments/show.html.erb
<h1>AdminTournaments#show</h1>
<p>Find me in app/views/admin_tournaments/show.html.erb</p>

app/views/match_movies/index.html.erb
<% @tournaments.each do |t| %>
    <h4><%= @all_tournaments[t - 1] %></h4>
    <% @movies.each do |m| %>
        <% if t == m.tournament_id %>
            <div class="py-1">
                <span>【<%= m.round %>】</span>
                <% movie_link = m.movie.slice(17..-1) %>
                <% img_link = "http://img.youtube.com/vi/" + movie_link + "/1.jpg" %>
                <%= link_to m.movie, class: "text-decoration-none", target: :_blank do %>
                    <div class="row justify-content-center text-decoration-none text-center">
                        <div class="col-5">
                            <img src=<%= img_link %> style="width: 120px; height: 68px; object-fit: cover;">
                        </div>
                        <div class="col-6">
                            <div>
                                <span><%= @all_players[m.player_a_id - 1] %></span>
                                <span>/</span>
                                <span><%= @all_players[m.player_b_id - 1] %></span>
                            </div>
                            <div>
                                <span>vs</span>
                            </div>
                            <div>
                                <span><%= @all_players[m.player_c_id - 1] %></span>
                                <span>/</span>
                                <span><%= @all_players[m.player_d_id - 1] %></span>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        <% end %>
    <% end %>
<% end %>

app/views/match_movies/search.html.erb
<div>
<%= form_with url: movies_search_path, class: "d-flex mb-3" do |form| %>
    <%= form.text_field :key, class: "form-control" %>
    <%= form.submit "検索", class: "form-control", style: "width: 20%" %>
<% end %>
</div>

<% if @movies %>
    <% @tournaments.each do |t| %>
        <h4><%= @all_tournaments[t - 1] %></h4>
        <% @movies.each do |m| %>
            <% if t == m.tournament_id %>
            <div class="py-1">
                <span>【<%= m.round %>】</span>

                <% movie_link = m.movie.slice(17..-1) %>
                <% img_link = "http://img.youtube.com/vi/" + movie_link + "/1.jpg" %>
                <%= link_to m.movie, class: "text-decoration-none", target: :_blank do %>
                    <div class="row justify-content-center text-decoration-none text-center">
                        <div class="col-5">
                            <img src=<%= img_link %> style="width: 120px; height: 68px; object-fit: cover;">
                        </div>

                        <div class="col-6">
                            <div>
                                <% if @player_id_list.include?(m.player_a_id) %>
                                    <span style="color:red"><%= @all_players[m.player_a_id - 1] %></span>
                                <% else %>
                                    <span><%= @all_players[m.player_a_id - 1] %></span>
                                <% end %>

                                <span>/</span>

                                <% if @player_id_list.include?(m.player_b_id) %>
                                    <span style="color:red"><%= @all_players[m.player_b_id - 1] %></span>
                                <% else %>
                                    <span><%= @all_players[m.player_b_id - 1] %></span>
                                <% end %>
                            </div>

                            <div>
                                <span>vs</span>
                            </div>

                            <div>
                                <% if @player_id_list.include?(m.player_c_id) %>
                                    <span style="color:red"><%= @all_players[m.player_c_id - 1] %></span>
                                <% else %>
                                    <span><%= @all_players[m.player_c_id - 1] %></span>
                                <% end %>

                                <span>/</span>

                                <% if @player_id_list.include?(m.player_d_id) %>
                                    <span style="color:red"><%= @all_players[m.player_d_id - 1] %></span>
                                <% else %>
                                    <span><%= @all_players[m.player_d_id - 1] %></span>
                                <% end %>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
            <% end %>
        <% end %>
    <% end %>
<% else %>
    <div>
        <p>選手名、大会名、所属、出身校などで検索可能です。</p>
        <p>例）船水、天皇杯、NTT、早稲田</p>
    </div>
<% end %>